import type { Course } from '../types'

export const linuxBasico: Course = {
  meta: {
    slug: 'linux-basico',
    title: 'Linux desde cero — los 20 comandos que necesitas',
    description:
      'Aprende Linux desde lo más básico: navegación, archivos, permisos y procesos. Sin instalar nada, todo desde el navegador. En español, con práctica real.',
    level: 'basico',
    totalLessons: 20,
    estimatedHours: 4,
  },
  lessons: [
    {
      slug: '01-pwd',
      title: 'pwd — ¿Dónde estoy?',
      description: 'Tu primer comando. Sirve para ver en qué directorio estás parado.',
      command: 'pwd',
      difficulty: 'basico',
      category: 'navegacion',
      readTime: 3,
      kind: 'terminal-linux',
    },
    {
      slug: '02-ls',
      title: 'ls — Ver qué hay',
      description: 'Lista archivos y carpetas en el directorio actual.',
      command: 'ls',
      difficulty: 'basico',
      category: 'navegacion',
      readTime: 4,
      kind: 'terminal-linux',
    },
    {
      slug: '03-cd',
      title: 'cd — Cambiar de directorio',
      description: 'Movete entre carpetas. El comando que más vas a usar.',
      command: 'cd',
      difficulty: 'basico',
      category: 'navegacion',
      readTime: 4,
      kind: 'terminal-linux',
    },
    {
      slug: '04-mkdir',
      title: 'mkdir — Crea directorios',
      description: 'Crea carpetas nuevas.',
      command: 'mkdir',
      difficulty: 'basico',
      category: 'archivos',
      readTime: 3,
      kind: 'terminal-linux',
    },
    {
      slug: '05-touch',
      title: 'touch — Crea archivos vacíos',
      description: 'Crea un archivo vacío o actualiza la fecha de uno existente.',
      command: 'touch',
      difficulty: 'basico',
      category: 'archivos',
      readTime: 2,
      kind: 'terminal-linux',
    },
    {
      slug: '06-cat',
      title: 'cat — Ver contenido de un archivo',
      description: 'Muestra todo el contenido de un archivo de texto en la terminal.',
      command: 'cat',
      difficulty: 'basico',
      category: 'texto',
      readTime: 4,
      kind: 'terminal-linux',
    },
    {
      slug: '07-less',
      title: 'less — Leer archivos grandes',
      description: 'Cuando cat no alcanza. Navega archivos largos con scroll.',
      command: 'less',
      difficulty: 'basico',
      category: 'texto',
      readTime: 4,
      kind: 'terminal-linux',
    },
    {
      slug: '08-cp',
      title: 'cp — Copia archivos',
      description: 'Copia un archivo o directorio a otra ubicación.',
      command: 'cp',
      difficulty: 'basico',
      category: 'archivos',
      readTime: 3,
      kind: 'terminal-linux',
    },
    {
      slug: '09-mv',
      title: 'mv — Mueve y renombrar',
      description: 'Mueve archivos o cámbiales el nombre.',
      command: 'mv',
      difficulty: 'basico',
      category: 'archivos',
      readTime: 3,
      kind: 'terminal-linux',
    },
    {
      slug: '10-rm',
      title: 'rm — Borra archivos',
      description: 'El comando peligroso. Borra archivos y directorios. Con cuidado.',
      command: 'rm',
      difficulty: 'basico',
      category: 'archivos',
      readTime: 4,
      kind: 'terminal-linux',
    },
    {
      slug: '11-echo',
      title: 'echo — Imprimir texto',
      description: 'Muestra un mensaje en la terminal o guardalo en un archivo.',
      command: 'echo',
      difficulty: 'basico',
      category: 'texto',
      readTime: 3,
      kind: 'terminal-linux',
    },
    {
      slug: '12-redirigir',
      title: '> y >> — Redirigir a archivo',
      description: 'Guarda la salida de un comando en un archivo.',
      command: 'redirigir',
      difficulty: 'intermedio',
      category: 'texto',
      readTime: 5,
      kind: 'terminal-linux',
    },
    {
      slug: '13-pipe',
      title: '| — El pipe, conectar comandos',
      description: 'La herramienta más poderosa: encadena comandos.',
      command: 'pipe',
      difficulty: 'intermedio',
      category: 'texto',
      readTime: 5,
      kind: 'terminal-linux',
    },
    {
      slug: '14-grep',
      title: 'grep — Busca texto',
      description: 'Busca palabras dentro de archivos o salidas.',
      command: 'grep',
      difficulty: 'intermedio',
      category: 'texto',
      readTime: 5,
      kind: 'terminal-linux',
    },
    {
      slug: '15-find',
      title: 'find — Busca archivos',
      description: 'Encuentra archivos por nombre, tamaño, fecha o tipo.',
      command: 'find',
      difficulty: 'intermedio',
      category: 'archivos',
      readTime: 5,
      kind: 'terminal-linux',
    },
    {
      slug: '16-chmod',
      title: 'chmod — Permisos de archivos',
      description: 'La parte confusa explicada simple. Cambia quién puede leer, escribir o ejecutar.',
      command: 'chmod',
      difficulty: 'intermedio',
      category: 'permisos',
      readTime: 7,
      kind: 'terminal-linux',
    },
    {
      slug: '17-sudo',
      title: 'sudo — Ejecuta como administrador',
      description: 'Haz cosas que requieren permisos especiales.',
      command: 'sudo',
      difficulty: 'intermedio',
      category: 'permisos',
      readTime: 4,
      kind: 'terminal-linux',
    },
    {
      slug: '18-ps',
      title: 'ps — Ver procesos corriendo',
      description: 'Qué programas están ejecutándose ahora en tu sistema.',
      command: 'ps',
      difficulty: 'intermedio',
      category: 'procesos',
      readTime: 5,
      kind: 'terminal-linux',
    },
    {
      slug: '19-kill',
      title: 'kill — Terminar procesos',
      description: 'Mata un proceso que se colgó o está consumiendo demasiado.',
      command: 'kill',
      difficulty: 'intermedio',
      category: 'procesos',
      readTime: 4,
      kind: 'terminal-linux',
    },
    {
      slug: '20-man',
      title: 'man — El manual de cualquier comando',
      description: 'Cómo aprender CUALQUIER comando nuevo tú mismo.',
      command: 'man',
      difficulty: 'basico',
      category: 'navegacion',
      readTime: 4,
      kind: 'terminal-linux',
    },
  ],
}
